---
title: 'CrowBase: comparisons with age bins'
author: "Justin Mann"
date: "3/9/2021"
output: html_document
---

Libraries
```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse) #ggplot2, dplyr, tibble, etc.
library(knitr)
library(ggfortify)
library(Rtsne)
library(usethis) #git integration
library(glmmTMB)
library(lme4)
library(ggpubr) #ggarrange() figure wraps
library(plyr)
library(ggeffects) #ggpredict
library(rstanarm) #stan models
library(shinystan) #stan model evaluation >launch_shinystan_demo()
library(loo) #loo() to compare fits between bayesian models
library(MuMIn) #dredge, model averaging
library(RColorBrewer) ; brewer.pal(n=8, name = "Dark2"); #display.brewer.pal(n = 8, name = "Dark2")
theme_set(theme_classic())
```




## Full dataframe (df). 
```{r}
df <- data.frame(read.csv("Nestlings1989-2018_no2011_WITH_AdultMeasurements_2001-2015.csv", h=T))
summary(df[,c(2:23)])
```

## Taking a peek at age distributions
```{r}
hist(df$calcAge[df$calcAge<100])
hist(df$calcAge[df$calcAge>100 & df$calcAge<5000])
hist(df$calcAge[df$calcAge<40])
```

## Create a vector and designate age bins 
### Note: These are somewhat arbitrarily chosen bins, which can be easily changed. Need direction in defining bins that are developmentally relevant.
```{r}
b <- c(-Inf,10,20,30,40,100,Inf) #define breaks
bins <- c("bin1","bin2","bin3","bin4","bin5","bin6") #label bins
df$ageBins <- cut(df$calcAge,breaks = b,labels = bins) #vectorize
df$ageBins <- as.factor(df$ageBins)
df$sexSummary <- as.factor(df$sexSummary)
```

```{r}
# cbind(df$calcAge,df$ageBins) #checking for correct binning 
#df$calcAge[df$ageBins == "bin2"]
```

#Bill Depth
```{r warning=FALSE}
df %>%
  drop_na(sexSummary,ageBins) %>% 
  ggplot(aes(x=ageBins,y=billD, fill=sexSummary))+
  geom_boxplot()+
  scale_fill_manual(values = c("#1B9E77","#E6AB02"),
                    name = "Sex",
                    labels = c("Female","Male"))+
  ylab("Bill depth (mm)")+
  scale_x_discrete(name = "Calculated age (days)",
                   breaks = c("bin1","bin2","bin3","bin4","bin5","bin6"),
                   labels = c("0-10","11-20","21-30","31-40","41-100",">100"))
```

#Bill width
```{r warning=FALSE}
df %>%
  drop_na(sexSummary,ageBins) %>% 
  filter(between(billW,1,90)) %>% #filter out one outlier > 90 in bin4 (??)
  ggplot(aes(x=ageBins,y=billW, fill=sexSummary))+
  geom_boxplot()+
  scale_fill_manual(values = c("#1B9E77","#E6AB02"),
                    name = "Sex",
                    labels = c("Female","Male"))+
  ylab("Bill width (mm)")+
  scale_x_discrete(name = "Calculated age (days)",
                   breaks = c("bin1","bin2","bin3","bin4","bin5","bin6"),
                   labels = c("0-10","11-20","21-30","31-40","41-100",">100"))
```

#Nares-to-tip
```{r warning=FALSE}
df %>%
  drop_na(sexSummary,ageBins) %>% 
  ggplot(aes(x=ageBins,y=billNT, fill=sexSummary))+
  geom_boxplot()+
  scale_fill_manual(values = c("#1B9E77","#E6AB02"),
                    name = "Sex",
                    labels = c("Female","Male"))+
  ylab("Bill nares-to-tip (mm)")+
  scale_x_discrete(name = "Calculated age (days)",
                   breaks = c("bin1","bin2","bin3","bin4","bin5","bin6"),
                   labels = c("0-10","11-20","21-30","31-40","41-100",">100"))
```

#Total exposed culmen
```{r warning=FALSE}
df %>%
  drop_na(sexSummary,ageBins) %>% 
  ggplot(aes(x=ageBins,y=TEC, fill=sexSummary))+
  geom_boxplot()+
  scale_fill_manual(values = c("#1B9E77","#E6AB02"),
                    name = "Sex",
                    labels = c("Female","Male"))+
  ylab("Total exposed culmen (mm)")+
  scale_x_discrete(name = "Calculated age (days)",
                   breaks = c("bin1","bin2","bin3","bin4","bin5","bin6"),
                   labels = c("0-10","11-20","21-30","31-40","41-100",">100"))
```
