---
title: "CrowNestlingClimate"
author: "Justin Mann"
date: "2022-11-01"
output: html_document
---

```{r libraries}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

## Dataframes for nestlings and climate metrics

```{r df}
nestlings.df <- read.csv("CleanedNestlings_FullMorphometrics_6.16.23.csv", h=TRUE)# 2098
climate.df <- read.csv("ClimateMetrics_ForJoining.csv", h=TRUE)
```

```{r join and write csv}
df <- left_join(nestlings.df,climate.df, by = "HatchDateJulYear")

df <- df %>% 
  relocate(Date, .before = HatchDateJulYear) %>% 
  relocate(CalcAge, .after = AllSex)

#trim some kids with impossible measurements (per Anne)
df <- df %>% 
  filter(Tarsus < 70) %>% #Tarsus must be > 70
  filter(CalcAge > 23.9) %>% #CalcAge must be > 23.9
  filter(Weight > 200) #Weight must be > 200

# New n=2085

df <- df %>% 
  relocate(c(Year,NestName), .before = "ID")


# write.csv(df, "CrowNestlingClimate_NestlingsCleaned&ClimateJoined_6.16.23.csv",
#          row.names = F)
```
