---
title: "Cleaning Unsexed Nestling Data"
author: "Justin Mann"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(dplyr)
library(broom) #tidy() to create tibbles from model summaries
library(car) #vif
library(cowplot)
library(lme4) #frequentist models  
library(sjPlot) #plot_model & tab_model (blue = #377EB8)
library(ggpubr) #ggarrange
library(glmmTMB) #zi & overdispersed models
library(lmerTest) #lmerTest::step
library(ggeffects) #ggpredict
#PACKAGES FOR BAYESIAN MODELS
library(rstanarm) #stan models
library(shinystan) #stan model evaluation
#launch_shinystan_demo()
library(loo) #use loo() to compare fits between bayesian models
library(plotly)
library(MuMIn) #dredge() for unsupervised model selection
library(AICcmodavg) #aictab() for AICc model comparisons
library(DHARMa)
library(DescTools)
theme_set(theme_classic())
```
<br>

```{r dataframe}
df <- read.csv("CrowNestlingClimate.csv", h=TRUE)
```
<br>

```{r Anne's laundry list}
#Find duplicate IDs 
duplicates.df <- df %>% group_by(ID) %>% filter(n()>1)

#list of duplicates sent to Anne
#write.csv(duplicates.df, "DuplicateNestlings.csv")

#Sort duplicates.df by year and CalcAge and only retain the first (youngest) observation
duplicates.df <- duplicates.df %>%  arrange(Year, CalcAge) %>% dplyr::distinct(Name, .keep_all = TRUE)

#Remove nestlings identified by Anne (runts/or suspect measurements)
#file name: Runt Nestlings so-called by year
df$ID[df$ID=="FFW-S DRIN02"]#in, remove below
df$ID[df$ID=="RFA-S	ALOT02"]#not in
df$ID[df$ID=="5	STAD96"]#not in
df$ID[df$ID=="Y-5 ROTA98"]#not in
df$ID[df$ID=="B3 WINK98"]#in, remove below
df$ID[df$ID=="B-1	WINK98"]#not in
df$ID[df$ID=="GL JSUP05"]#in, remove below
df$ID[df$ID=="CV WKAY05"]#not in 
df$ID[df$ID=="YB-OSW HORC10"]#not in 
df$ID[df$ID=="FE WCRI18"]#in, remove below
df$ID[df$ID=="Q4 CARE11"]#in, remove below
df$ID[df$ID=="OD CCPL02"]#not in
df$ID[df$ID=="*00 WCRI14"]#not in
df$ID[df$ID=="JC NDYC17"]#in, remove below
df$ID[df$ID=="Dead under nest	MIPA14"]#not in
df$ID[df$ID=="L-2 KRUM93"]#in, remove below
df$ID[df$ID=="orange SWEG91"]#in, remove below
df$ID[df$ID=="SWB-W BURP03"]#in, remove below
df$ID[df$ID=="3 PINW00"]#in, remove below
df$ID[df$ID=="4 PINW00"]#in, remove below
df$ID[df$ID=="DOA RGBY00"]#in, remove below
df$ID[df$ID=="doa SEPG04"]#in, remove below
df$ID[df$ID=="2-r HORC04"]#in, remove below
df$ID[df$ID=="doa CLAR05"]#in, remove below
df$ID[df$ID=="doa HOMC05"]#in, remove below
df$ID[df$ID=="doa JUDD06"]#in, remove below
df$ID[df$ID=="doa1 KAYS06"]#in, remove below
df$ID[df$ID=="doa2 KAYS06"]#in, remove below
df$ID[df$ID=="doa3 KAYS06"]#in, remove below
df$ID[df$ID=="doa1 BROT07"]#in, remove below
df$ID[df$ID=="doa2 BROT07"]#in, remove below
df$ID[df$ID=="doa1 NMUR07"]#in, remove below
df$ID[df$ID=="doa2 NMUR07"]#in, remove below
df$ID[df$ID=="doa3 NMUR07"]#in, remove below
df$ID[df$ID=="doa4 NMUR07"]#in, remove below
df$ID[df$ID=="doa5 NMUR07"]#in, remove below

#Remove individuals listed above
df <- df %>% filter(!ID %in% c("FFW-S DRIN02","B3 WINK98","GL JSUP05","Q4 CARE11","JC NDYC17",
                           "L-2 KRUM93","orange SWEG91","SWB-W BURP03","3 PINW00","4 PINW00",
                           "doa SEPG04","2-r HORC04","doa CLAR05","doa HOMC05","doa JUDD06",
                           "doa1 KAYS06","doa2 KAYS06","doa3 KAYS06","doa1 BROT07","doa2 BROT07",
                           "doa1 NMUR07","doa2 NMUR07","doa3 NMUR07","doa4 NMUR07","doa5 NMUR07"))
```


```{r select and rename variables}
#Select variables
df <- df %>% 
  select(Year,Name,NestName,ID,AgeField,CalcAge,HatchDateJul,HatchDateJulYear,AllSex,BillNT,BillWidth,BillDepth,TEC,Head,UpperBill,UBillSurface,TotBillSurface,Skull,Tarsus,Weight)

#Rename variables
df <- df %>% 
  rename(FieldAge=AgeField,BNT=BillNT,BW=BillWidth,BD=BillDepth,UB=UpperBill,UBS=UBillSurface,TBS=TotBillSurface)
```
<br>

```{r count NAs}
#Count NAs
countNAs <- sapply(df, function(x) sum(is.na(x)))
countNAs
```

```{r remove NAs and double check}
#Remove NAs
df <- df %>% 
  filter_at(vars(Weight,HatchDateJul,BD,Tarsus,Skull,BW), all_vars(!is.na(.)))

#Recount NAs
countNAs <- sapply(df, function(x) sum(is.na(x)))
countNAs
```
<br> 

```{r filters}
#filter out names with 'doa' or 'dead'
#df <- df %>% filter(!grepl("doa|dead",Name))

#filter out Weights < 160 
df <- df %>% filter(Weight > 160)
range(df$Weight)
```


```{r plot Weight by FieldAge}
WeightByFieldAge.plot <- ggplot(data = df, aes(x=FieldAge,y=Weight,label=ID,color=HatchDateJul))+
  geom_point()
ggplotly(WeightByFieldAge.plot)
```


```{r CalcAge filter (24-30)}
df <- df %>% filter(between(CalcAge, 24,30))
range(df$CalcAge)
```


```{r plot Weight by CalcAge}
WeightByCalcAge.plot <- ggplot(data = df, aes(x=CalcAge,y=Weight,label=ID))+
  geom_point()
ggplotly(WeightByCalcAge.plot)
```


```{r read in climate data}
climate.df <- read.csv("ClimateMetrics.csv", h=TRUE)
```


```{r joining nestling and climate data}
df <- left_join(df,climate.df, by = "HatchDateJulYear")
df <- df %>% relocate(Date, .before = AllSex)
#write.csv(df, "AllNestlingsClimateJoined.csv")
```

```{r scaling}
#variables that don't get scaled 
DataNotScaled.df <- df[,1:10]

#Numerical data that do get scaled
DataToScale.df <- df[,11:39]

#Scale those data
Scaled.df <- scale(DataToScale.df)

#Rejoin with variables that don't get scaled
scaled.df <- cbind(DataNotScaled.df,Scaled.df)
```


```{r BD model}
BD.scaled.mdl <- lm(data = scaled.df, BD ~ GDDSum12_22 * PrecipSum12_22 + Weight + CalcAge)
summary(BD.scaled.mdl)
```

