---
title: "CrowBase-AdultsSumStats"
author: "Justin Mann"
date: "2/17/2021"
output: html_document
---

Exploring adult measurement data. 

'AdultData_OffBase.csv' file contains all NET and other incidental adult birds measured between 2001-2015 as per Google Drive CRG Reference Files.

```{r message=FALSE, warning=FALSE}
library(tidyverse) 
library(usethis) #git integration
library(tibble)
library(ggpubr) #ggarrange() figure wraps
library(plyr)
theme_set(theme_classic())
```


```{r}
adults <- read.csv("AdultData_OffBase.csv", h=TRUE)
```
```{r}
as_tibble(adults)
```



```{r}
summary(adults)
```


```{r sppMetrics, out.width='95%'}
sppWeight <- adults %>%
  ggplot(aes(x=species, y=weight))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppTEC <- adults %>%
  ggplot(aes(x=species, y=tec))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppWing <- adults %>%
  ggplot(aes(x=species, y=wingChord))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank()) 

sppTail <- adults %>%
  ggplot(aes(x=species, y=tailLength))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppBillNT <- adults %>%
  ggplot(aes(x=species, y=billNT))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppBillW <- adults %>%
  ggplot(aes(x=species, y=billWidth))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppBillD <- adults %>%
  ggplot(aes(x=species, y=billDepth))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppHead <- adults %>%
  ggplot(aes(x=species, y=head))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppTarsus <- adults %>%
  ggplot(aes(x=species, y=tarsus))+
  geom_boxplot()+
  geom_jitter(shape=1)+
  theme(axis.title.x = element_blank())

sppMetrics <- suppressWarnings(ggarrange(sppWeight,sppTEC,sppWing,sppTail,sppBillNT,sppBillW,sppBillW,sppHead,sppTarsus))

print(sppMetrics)
```
Suspect measurement of fish crow for BillNT needs checking--row 133, 8Q GENR05, 158mm (was temporarily removed)  
