---
title: "CrowNestlingClimate"
author: "Justin Mann"
date: "2022-11-01"
output: html_document
---

```{r libraries}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lme4) #frequentist models  
library(sjPlot) #plot_model & tab_model (blue = #377EB8)
library(ggpubr) #ggarrange
library(glmmTMB) #zi & overdispersed models
library(lmerTest) #lmerTest::step
library(ggeffects) #ggpredict
library(rstanarm) #stan models
library(shinystan) #stan model evaluation
#launch_shinystan_demo()
library(loo) #use loo() to compare fits between bayesian models
library(plotly)
library(MuMIn) #dredge() for unsupervised model selection
library(AICcmodavg) #aictab() for AICc model comparisons
```

## Prototype Dataframe

```{r df}
nestlings <- read.csv("CrowNestlingClimate.csv", h=TRUE)
nestlings <- nestlings[,1:33]
nestlings <- nestlings %>% 
  filter(Year!=1989)
climate <- read.csv("ClimateMetrics.csv", h=TRUE)
climate <- climate %>% 
  select(Month, Day, HatchDateJul,MaxTempMean1_11,MaxTempMean12_22, MeanMaxTempIncubation,PrecipSum1_11,PrecipSum12_22,PrecipSumIncubation,GDDSum1_11,GDDSum12_22,GDDSumIncubation,CDDSum1_11,CDDSum12_22,CDDSumIncubation)
```

```{r}
df <- left_join(nestlings,climate, by = "HatchDateJul")
write.csv(df, "CrowNestlingClimateJoined.csv")
```


## Pairs Plots

```{r}
?pairs()
pairs(df[,c(7,11:14,28:32,48)])
```

```{r}
glmer(billArea~,data = df)
```

