---
title: "Calculating Climate Metrics"
author: "Justin Mann"
date: "2022-09-27"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(dplyr)
library(zoo)
library(lubridate)
```

## CLIMOD2 Data for Cornell University Weather Station
8 Game Farm Rd, Ithaca, NY 14850
Station IDs:
304174 (Coop)
USC00304174 (GHCN)
ITHN6 (NWS LI)

<http://www.nrcc.cornell.edu/>

<http://climod2.nrcc.cornell.edu/>

```{r raw data}
#Raw text file downloaded from climod2
rawclim.df <- read.table("climod2data1989-2022.txt", sep = ",", header = TRUE)

#Make variables numeric (will coerce NAs where data are missing)
rawclim.df$MaxTemp <- as.numeric(rawclim.df$MaxTemperature)
which(is.na(rawclim.df$MaxTemp))#[1] 1535
rawclim.df$MinTemp <- as.numeric(rawclim.df$MinTemperature)
which(is.na(rawclim.df$MinTemp))#[1] 1440 1536 1853 4401

rawclim.df$Precip <- as.numeric(rawclim.df$Precipitation)
rawclim.df$Snowfall <- as.numeric(rawclim.df$Snowfall)
rawclim.df$SnowDepth <- as.numeric(rawclim.df$SnowDepth)  
```

```{r metric and celcius conversions}
f2c <- function(x){
  x <- (5/9) * (x-32)
  return(x)
}
f2c(33)#[1] 0.556

rawclim.df$MaxC <- mapply(f2c, rawclim.df$MaxTemp)
rawclim.df$MinC <- mapply(f2c, rawclim.df$MinTemp)

in2cm <- function(x){
  x <- x * 2.54
  return(x)
}
in2cm(0.1)#[1] 0.254

rawclim.df$PrecipCM <- mapply(in2cm, rawclim.df$Precip)
rawclim.df$SnowfallCM <- mapply(in2cm, rawclim.df$Snowfall)
rawclim.df$SnowDepthCM <- mapply(in2cm, rawclim.df$SnowDepth)
```

```{r}
#clim.df <- read.csv("ClimateMetrics_AllMonths1989-2022.csv", h=TRUE)
```


```{r new data frame}
clim.df <- rawclim.df %>% 
  select(Date,MaxC,MinC,
         PrecipCM,SnowfallCM,SnowDepthCM)
#add year column
clim.df$Year <- lubridate::year(clim.df$Date)
#add Julian Day
clim.df$JulDay <- lubridate::yday(clim.df$Date)
#pad Julian Day with zeros
clim.df$JulDay <- str_pad(clim.df$JulDay, 3, pad = "0")
#join padded Julian Days with Year
my_cols <- c("Year", "JulDay")
clim.df$HatchDateJulYear <- do.call(paste, c(clim.df[my_cols], sep = ""))
```
<br>

Now, we'll create some potentially biologically-relevant temperature thresholds 
```{r temperature thesholds}
#add daily mean column
clim.df$MeanC <- (clim.df$MaxC + clim.df$MinC)/2

#add columns where daily mean temperatures are set relative to 
#5 degrees C
clim.df$C5 <- clim.df$MeanC - 5
#10 degrees C
clim.df$C10 <- clim.df$MeanC - 10
#15 degrees C
clim.df$C15 <- clim.df$MeanC - 15
#20 degrees C
clim.df$C20 <- clim.df$MeanC - 20

#make maximum temp relative to C10 without mean
clim.df$MaxC10 <- clim.df$MaxC - 10
#make minimum temp relative to C1 without mean
clim.df$MinC1 <- 1 - clim.df$MinC
1-(-6.6) 
```

```{r write a new climate metric csv}
clim.df <- clim.df %>% 
  relocate(c(MinC, MaxC), .after = SnowDepthCM)
```

```{r clim.df}
#clim.df <- read.csv("ClimateMetrics_AllMonths1989-2022.csv", h=T)
```
<br>


## Maximum temperature rolling means
```{r MeanMax1_11}
#An 11-day rolling window calculates the mean of MaxC for post-hatch days 1-11
clim.df$MeanMax1_11 <- zoo::rollapply(clim.df$MaxC, width=11, FUN=mean, align = 'left', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(mean=mean(clim.df[1:11,9]),metric=clim.df[1,15])
#mean() calculation should match metric
```

```{r MeanMax12_22}
#An 11-day rolling window calculates the mean of MaxC for post-hatch days 12-22
clim.df$MeanMax12_22 <- dplyr::lead(clim.df$MeanMax1_11, n = 11)

#Code check
c(mean=mean(clim.df[12:22,9]), metric=clim.df[1,16])#mean() calculation should match metric
```

```{r MeanMaxIncubation}
#MaxC mean for 19 days prior to hatch date
clim.df$MeanMaxIncubation <- zoo::rollapply(clim.df$MaxC, width=19, FUN=mean, align = 'right', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(mean=mean(clim.df[1:19,9]), metric=clim.df[19,17]) #mean() calculation should match metric
```
<br>


## Minimum temperature rolling means
```{r MeanMin1_11}
#An 11-day rolling window calculates the mean of MinC for post-hatch days 1-11
clim.df$MeanMin1_11 <- zoo::rollapply(clim.df$MinC, width=11, FUN=mean, align = 'left', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(mean=mean(clim.df[1:11,8]),metric=clim.df[1,18])
#mean() calculation should match metric
```

```{r MeanMin12_22}
#An 11-day rolling window calculates the mean of MinC for post-hatch days 12-22
clim.df$MeanMin12_22 <- dplyr::lead(clim.df$MeanMin1_11, n = 11)

#Code check
c(mean=mean(clim.df[12:22,8]), metric=clim.df[1,19])#mean() calculation should match metric
```

```{r MeanMinIncubation}
#MinC mean for 19 days prior to hatch date
clim.df$MeanMinIncubation <- zoo::rollapply(clim.df$MinC, width=19, FUN=mean, align = 'right', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(mean=mean(clim.df[1:19,8]), metric=clim.df[19,20]) #mean() calculation should match metric
```
<br>


## C5 rolling sums
```{r C5Sum1_11}
#An 11-day rolling window calculates the mean of C5 for post-hatch days 1-11
clim.df$C5Sum1_11 <- zoo::rollapply(clim.df$C5, width=11, FUN=sum, align = 'left', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:11,11]),metric=clim.df[1,21])
#mean() calculation should match metric
```

```{r C5Sum12_22}
#An 11-day rolling window calculates the mean of C5 for post-hatch days 12-22
clim.df$C5Sum12_22 <- dplyr::lead(clim.df$C5Sum1_11, n = 11)

#Code check
c(sum=sum(clim.df[12:22,11]), metric=clim.df[1,22])#mean() calculation should match metric
```

```{r C5SumIncubation}
#C5 mean for 19 days prior to hatch date
clim.df$C5SumIncubation <- zoo::rollapply(clim.df$C5, width=19, FUN=sum, align = 'right', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:19,11]), metric=clim.df[19,23]) #mean() calculation should match metric
```
<br>


## C10 rolling sums
```{r C10Sum1_11}
#An 11-day rolling window calculates the mean of C10 for post-hatch days 1-11
clim.df$C10Sum1_11 <- zoo::rollapply(clim.df$C10, width=11, FUN=sum, align = 'left', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:11,12]),metric=clim.df[1,24])
#mean() calculation should match metric
```

```{r C10Sum12_22}
#An 11-day rolling window calculates the mean of C10 for post-hatch days 12-22
clim.df$C10Sum12_22 <- dplyr::lead(clim.df$C10Sum1_11, n = 11)

#Code check
c(sum=sum(clim.df[12:22,12]), metric=clim.df[1,25])#mean() calculation should match metric
```

```{r C10SumIncubation}
#C10 mean for 19 days prior to hatch date
clim.df$C10SumIncubation <- zoo::rollapply(clim.df$C10, width=19, FUN=sum, align = 'right', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:19,12]), metric=clim.df[19,26]) #mean() calculation should match metric
```
<br>


## C15 rolling sums
```{r C15Sum1_11}
#An 11-day rolling window calculates the mean of C15 for post-hatch days 1-11
clim.df$C15Sum1_11 <- zoo::rollapply(clim.df$C15, width=11, FUN=sum, align = 'left', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:11,13]),metric=clim.df[1,27])
#mean() calculation should match metric
```

```{r C15Sum12_22}
#An 11-day rolling window calculates the mean of C15 for post-hatch days 12-22
clim.df$C15Sum12_22 <- dplyr::lead(clim.df$C15Sum1_11, n = 11)

#Code check
c(sum=sum(clim.df[12:22,13]), metric=clim.df[1,28])#mean() calculation should match metric
```

```{r C15SumIncubation}
#C15 mean for 19 days prior to hatch date
clim.df$C15SumIncubation <- zoo::rollapply(clim.df$C15, width=19, FUN=sum, align = 'right', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:19,13]), metric=clim.df[19,29]) #mean() calculation should match metric
```
<br>


## Precip rolling sums
```{r PrecipSum1_11}
#An 11-day rolling window calculates the mean of PrecipCM for post-hatch days 1-11
clim.df$PrecipSum1_11 <- zoo::rollapply(clim.df$PrecipCM, width=11, FUN=sum, align = 'left', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:11,5], na.rm = T),metric=clim.df[1,30])
#mean() calculation should match metric
```

```{r PrecipSum12_22}
#An 11-day rolling window calculates the mean of PrecipCM for post-hatch days 12-22
clim.df$PrecipSum12_22 <- dplyr::lead(clim.df$PrecipSum1_11, n = 11)

#Code check
c(sum=sum(clim.df[12:22,5], na.rm = T), metric=clim.df[1,31])#mean() calculation should match metric
```

```{r PrecipSumIncubation}
#PrecipCM mean for 19 days prior to hatch date
clim.df$PrecipSumIncubation <- zoo::rollapply(clim.df$PrecipCM, width=19, FUN=sum, align = 'right', fill = NA, partial = TRUE, na.rm = TRUE)

#Code check
c(sum=sum(clim.df[1:19,5], na.rm = T), metric=clim.df[19,32]) #mean() calculation should match metric
```
<br>








```{r simplified df for analysis}
#New dataframe with the derived climate metrics
clim.df <- clim.df %>% 
  select(Date,HatchDateJulYear,
         MeanMax1_11,MeanMax12_22,MeanMaxIncubation,
         MeanMin1_11,MeanMin12_22,MeanMinIncubation,
         PrecipSum1_11,PrecipSum12_22,PrecipSumIncubation,
         C5Sum1_11,C5Sum12_22,C5SumIncubation,
         C10Sum1_11,C10Sum12_22,C10SumIncubation,
         C15Sum1_11,C15Sum12_22,C15SumIncubation)
```

```{r}
write.csv(clim.df, "ClimateMetrics_ForJoining.csv", row.names = FALSE)
```



