---
title: "Joining Climate and Nestlings"
author: "Justin Mann"
date: "2022-10-28"
output: html_document
---

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(lme4) #frequentist models  
library(sjPlot) #plot_model & tab_model (blue = #377EB8)
library(ggpubr) #ggarrange
library(glmmTMB) #zi & overdispersed models
library(ggbiplot) #pca plots
library(lmerTest) #lmerTest::step
library(ggeffects) #ggpredict
library(rstanarm) #stan models
library(shinystan) #stan model evaluation
library(DescTools) #Dunn's rank sum test
library(loo) #use loo() to compare fits between bayesian models
library(BayesianFirstAid) #bayes.prop.test for comparison of response between groups
launch_shinystan_demo()
```

## Import Nestling Data

```{r N.df = nestling dataframe}
N.df <- read.csv("nestlingMorph.csv", h=TRUE)
N.df <- filter(N.df, population == "Ithaca" & species == "AMCR")
summary(as.factor(N.df$species))
```

## Import and join the new sexing data to Nestling dataframe 

```{r S.df = sexing dataframe}
S.df <- read.csv("CrowBloodSexing_2010-2022.csv", h=TRUE)
#Filter to only individuals with sexes
S.df <- filter(S.df, sex == c("M","F"))
#New sexing dataframe with only sex and id
S.df <- S.df %>% 
  select(id, sex)
```


```{r updating sexes}
#Nestling dataframe with only sex and id
Ns.df  <- N.df %>% 
  select(id, sex)
#Update Ns.df with new sexing data 
Ns.df <- Ns.df %>%   
  rows_update(S.df, by = "id", unmatched = "ignore")
#Replace old column with sexes missing with the new column with new sexes added
N.df$sex <- Ns.df$sex
write.csv(N.df, "NestlingSexesUpdated.csv")
```

## Attempting a join of birds that currently have hatching dates 

```{r filter to only birds with hatch dates}
N.df <- read.csv("NestlingSexesUpdated.csv", h=TRUE)

#Select id and measurement date from N.df
Nmc.df <- N.df %>% 
  select(id,measurementDate)

#Grabbing missing measurement dates from mouth color dataset
MC.df <- read.csv("CB-mouthColor.csv", h=TRUE)
#Select id and measurement date
MC.df <- MC.df %>% 
  select(id,measurementDate)
#Update rows to add mouthColor measurement dates
Nmc.df <- Nmc.df %>%   
  rows_update(MC.df, by = "id", unmatched = "ignore")
#Replace old column with missing dates with the new column with MC dates added
N.df$measurementDate <- Nmc.df$measurementDate
write.csv(N.df, "NestlingMDatesUpdated.csv")




H.df <- N.df %>% 
  filter(N.df, hatchDate!="?")
```

